import { ChangeEvent, useEffect, useState } from "react";
import { invoke } from "@tauri-apps/api/core";
import { open } from "@tauri-apps/plugin-dialog";
import GraphView from "./components/GraphView";
import Sidebar from "./components/Sidebar";
import BookmarksPanel from "./components/BookmarksPanel";
import { useAnalysisStore } from "./state/store";
import { AnalysisResult, CURRENT_SCHEMA_VERSION } from "./types";
import {
  isSchemaVersionCompatible,
  validateAnalysisResult,
} from "./validation";

const isTauri = Boolean(import.meta.env.TAURI_PLATFORM);

const App = () => {
  const loadAnalysis = useAnalysisStore((state) => state.loadAnalysis);
  const analysis = useAnalysisStore((state) => state.analysis);
  const [error, setError] = useState<string | null>(null);
  const [isDragging, setIsDragging] = useState(false);
  const [isAnalyzing, setIsAnalyzing] = useState(false);

  const loadAnalysisFromText = async (raw: string) => {
    try {
      const rawValue = JSON.parse(raw);
      const result = validateAnalysisResult(rawValue);

      if (!result.ok) {
        console.error("Schema validation failed", result.error, rawValue);
        setError(
          "The analysis file is not a valid Astrograph analysis (missing or invalid fields).",
        );
        return;
      }

      const { value } = result;

      if (!isSchemaVersionCompatible(value.schema_version)) {
        console.error(
          "Schema version mismatch",
          value.schema_version,
          `expected ${CURRENT_SCHEMA_VERSION}`,
        );
        const message =
          value.schema_version > CURRENT_SCHEMA_VERSION
            ? `This analysis file uses schema version ${value.schema_version}, which is newer than this UI supports. Please update Astrograph and try again.`
            : `This analysis file was generated by an incompatible Astrograph schema version (${value.schema_version}). Please regenerate the analysis with the current CLI.`;
        setError(message);
        return;
      }

      loadAnalysis(value);
      setError(null);
    } catch (err) {
      console.error(err);
      setError(
        "Unable to parse analysis JSON. Make sure it's a valid Astrograph output file.",
      );
    }
  };

  const handleFileLoad = async (event: ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) {
      return;
    }
    const raw = await file.text();
    await loadAnalysisFromText(raw);
  };

  const handleAnalyzeProject = async () => {
    try {
      setError(null);
      const selected = await open({
        directory: true,
        multiple: false,
      });
      if (selected == null) {
        return;
      }
      setIsAnalyzing(true);
      const path = typeof selected === "string" ? selected : String(selected);
      const result = await invoke<AnalysisResult>("analyze_project_dir", { path });
      loadAnalysis(result);
    } catch (err) {
      console.error(err);

      // Tauri v2 wraps backend errors in an Error with a `payload` field.
      // See https://tauri.app for details on the error shape.
      const anyErr = err as unknown as { payload?: { code?: string; message?: string } };
      const payload = anyErr?.payload;

      if (payload?.code) {
        switch (payload.code) {
          case "invalid_path":
            setError("Selected path does not exist.");
            break;
          case "not_directory":
            setError("Please select a directory, not a file.");
            break;
          case "io_error":
            setError(
              "Could not read files from the selected directory. Check permissions.",
            );
            break;
          case "analysis_failed":
            setError("Analysis failed unexpectedly. See logs for details.");
            break;
          default:
            setError(payload.message || "Analysis failed.");
            break;
        }
      } else {
        const message = err instanceof Error ? err.message : String(err);
        setError(message || "Analysis failed.");
      }
    } finally {
      setIsAnalyzing(false);
    }
  };

  // Drag and drop support
  useEffect(() => {
    const handleDragOver = (e: DragEvent) => {
      e.preventDefault();
      setIsDragging(true);
    };

    const handleDragLeave = (e: DragEvent) => {
      e.preventDefault();
      setIsDragging(false);
    };

    const handleDrop = async (e: DragEvent) => {
      e.preventDefault();
      setIsDragging(false);

      const file = e.dataTransfer?.files[0];
      const isJson =
        file &&
        (file.type === "application/json" ||
          file.name.toLowerCase().endsWith(".json"));
      if (isJson) {
        const raw = await file.text();
        await loadAnalysisFromText(raw);
      }
    };

    window.addEventListener("dragover", handleDragOver);
    window.addEventListener("dragleave", handleDragLeave);
    window.addEventListener("drop", handleDrop);

    return () => {
      window.removeEventListener("dragover", handleDragOver);
      window.removeEventListener("dragleave", handleDragLeave);
      window.removeEventListener("drop", handleDrop);
    };
  }, []);

  return (
    <div className={`app ${isDragging ? "dragging" : ""}`}>
      <header className="app-header">
        <div className="logo">✦ Astrograph</div>
        <div className="header-actions">
          {isTauri && (
            <button
              type="button"
              className="file-button"
              onClick={handleAnalyzeProject}
              disabled={isAnalyzing}
            >
              {isAnalyzing ? "Analyzing…" : "Analyze project"}
            </button>
          )}
          <label className="file-button">
            Load analysis
            <input
              type="file"
              accept="application/json"
              onChange={handleFileLoad}
            />
          </label>
          {analysis && (
            <div className="header-meta">
              <span>{analysis.stats.file_count} files</span>
              <span>{analysis.stats.symbol_count} symbols</span>
              <span>{analysis.stats.call_count} calls</span>
            </div>
          )}
        </div>
      </header>
      {isTauri && isAnalyzing && !error && (
        <div className="info-banner">Analyzing project… This may take a few moments.</div>
      )}
      {error && <div className="error-banner">{error}</div>}
      {isDragging && (
        <div className="drop-overlay">
          <div className="drop-message">Drop analysis.json here</div>
        </div>
      )}
      <div className="app-body">
        <Sidebar />
        <main className="graph-panel">
          <GraphView />
        </main>
        <BookmarksPanel />
      </div>
    </div>
  );
};

export default App;
